### ISSUE TITLE
Which data is sent to Nubo Software Ltd.? GDPR compliance?

### ISSUE THREAD

**Issue by M-Stenzel** [nubosoftware/linux-remote-desktop#8]
Hi team,

in the frontend I saw this setting:

---
"NotificationGateway": {
    "smsUrl": "https://gl.nubosoftware.com/SmsNotification/sendSmsNotificationFromRemoteServer",
    "url": "https://gl.nubosoftware.com/Notifications/sendNotificationFromRemoteServer",
    "serverID": "DEFAULT",
    "authKey": "DEFAULT"
  },
---

May I kindly ask you which kind of data is sent to Nubo Software Ltd.?
Is this anonymised? Is there an opt-out rule?
I wonder about GDPR compliance,

thank you in advance,

Martin.

**Comment by nubosoftware** [comment]
Hi Martin,

This setting is not relevant to the desktop version and it does not send any data. You can safely remove or change the settings.

In the mobile version, this is used to send notifications from apps running in the server to a physical phone running our thin client app. We do not control the content of the notification as it is sent by the mobile apps that are running in the platform.

Best regards,
Nubo Team
